#antispam

#time in seconds a player has to wait to send a message again
time: 1
#max warnings a player will receive until they receive a block type
max_warnings: 2
#warn player each time they spam
warning_message: "§ePlease stop chatting too quick! §cWarnings:§6 %warns%"
#message that will be sent if player is spamming
#%player% = players name
kick_reason: "§aYou have been kicked for spamming."

#bad words
messages:
- fuck
identify-capital-alphabet: false
mosaic: '*'
